#ifndef LANCE_GO_H
#define LANCE_GO_H

/* WARNING: this file is auto-generated by cbindgen from rust/src. Do not edit by hand; run `make rust` to regenerate. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#ifndef ARROW_C_DATA_INTERFACE
#define ARROW_C_DATA_INTERFACE

#define ARROW_FLAG_DICTIONARY_ORDERED 1
#define ARROW_FLAG_NULLABLE 2
#define ARROW_FLAG_MAP_KEYS_SORTED 4

struct ArrowSchema {
  /* Array type description */
  const char* format;
  const char* name;
  const char* metadata;
  int64_t flags;
  int64_t n_children;
  struct ArrowSchema** children;
  struct ArrowSchema* dictionary;

  /* Release callback */
  void (*release)(struct ArrowSchema*);
  /* Opaque producer-specific data */
  void* private_data;
};

struct ArrowArray {
  /* Array data description */
  int64_t length;
  int64_t null_count;
  int64_t offset;
  int64_t n_buffers;
  int64_t n_children;
  const void** buffers;
  struct ArrowArray** children;
  struct ArrowArray* dictionary;

  /* Release callback */
  void (*release)(struct ArrowArray*);
  /* Opaque producer-specific data */
  void* private_data;
};

#endif  /* ARROW_C_DATA_INTERFACE */

#ifndef ARROW_C_STREAM_INTERFACE
#define ARROW_C_STREAM_INTERFACE

struct ArrowArrayStream {
  int (*get_schema)(struct ArrowArrayStream*, struct ArrowSchema* out);
  int (*get_next)(struct ArrowArrayStream*, struct ArrowArray* out);
  const char* (*get_last_error)(struct ArrowArrayStream*);
  void (*release)(struct ArrowArrayStream*);
  void* private_data;
};

#endif  /* ARROW_C_STREAM_INTERFACE */


// ABI version of the complete lance-go native interface. This is separate
// from `LANCE_GO_VTABLE_ABI_VERSION`, which versions only the callback table.
// Bump this whenever a C signature, error code, ownership convention, or
// internal JSON wire contract changes incompatibly.
#define LANCE_GO_ABI_VERSION 1

// ABI version of [`LanceGoVTable`]. Bump on any breaking change to the
// vtable layout or calling conventions. [`lance_register_go_vtable`]
// rejects mismatches.
#define LANCE_GO_VTABLE_ABI_VERSION 1

// `invoke` succeeded. The out buffer holds the response payload (a NULL out
// buffer means an empty response).
#define LANCE_GO_CALL_OK 0

// `invoke` failed. The out buffer holds a UTF-8 error message.
#define LANCE_GO_CALL_ERROR 1

// `invoke` reports "not found" / cache miss, with no out buffer.
#define LANCE_GO_CALL_MISS 2

// Delta row kinds accepted by `lance_dataset_delta`.
#define LANCE_DELTA_INSERTED 0

// See [`LANCE_DELTA_INSERTED`].
#define LANCE_DELTA_UPDATED 1

// See [`LANCE_DELTA_INSERTED`].
#define LANCE_DELTA_UPSERTED 2

// Error codes returned by fallible `lance_*` functions.
//
// Mirrored by the sentinel errors in the Go package
// (`lance.ErrInvalidArgument`, `lance.ErrIO`, ...).
enum ErrorCode
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  ERROR_CODE_OK = 0,
  ERROR_CODE_INVALID_ARGUMENT = 1,
  ERROR_CODE_IO = 2,
  ERROR_CODE_NOT_FOUND = 3,
  ERROR_CODE_ALREADY_EXISTS = 4,
  ERROR_CODE_INDEX = 5,
  ERROR_CODE_INTERNAL = 6,
  ERROR_CODE_NOT_IMPLEMENTED = 7,
  ERROR_CODE_CONFLICT = 8,
  ERROR_CODE_TIMEOUT = 9,
  // The calling thread's cancellation token fired before the operation
  // completed (see `crate::runtime`). Never produced by `map_lance_error`.
  ERROR_CODE_CANCELLED = 10,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ErrorCode ErrorCode;
#else
typedef int32_t ErrorCode;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// Opaque handle to a single blob file returned by `take_blobs`. Borrowed from
// its [`LanceBlobList`], valid until the list is closed.
typedef struct LanceBlobFile LanceBlobFile;

// Opaque, owning list of blob files. Release with `lance_blob_list_close`.
//
// The `Vec` is built once and never mutated, so element addresses stay stable
// for the list's lifetime. `lance_blob_list_get` hands out borrowed pointers
// into it.
typedef struct LanceBlobList LanceBlobList;

// Opaque handle to a cancellation token shared between Go and this library.
// Created by [`lance_cancel_token_new`], cancelled (from any thread) with
// [`lance_cancel_token_cancel`], and released with
// [`lance_cancel_token_free`].
typedef struct LanceCancelToken LanceCancelToken;

// Opaque handle to an opened Lance dataset. Created by `lance_dataset_open`
// or `lance_dataset_write`. Must be released with `lance_dataset_close`.
typedef struct LanceDataset LanceDataset;

// Opaque handle to a single fragment of a Lance dataset. Created by
// `lance_dataset_get_fragment`. Must be released with `lance_fragment_close`.
// Self-contained: the wrapped fragment snapshots the dataset, so the handle
// outlives the originating dataset handle.
typedef struct LanceFragment LanceFragment;

// Opaque handle to a configured scan over a Lance dataset. Created by
// `lance_scanner_new`. Must be released with `lance_scanner_close`. The
// scanner snapshots the dataset internally, so it stays valid even if the
// originating dataset handle is closed first.
typedef struct LanceScanner LanceScanner;

// Opaque handle to a [`Session`]. Created by `lance_session_new` /
// `lance_session_new_with_cache_backend`. Released with
// `lance_session_close`.
typedef struct LanceSession LanceSession;

// Table of C function pointers implemented by cgo-exported Go functions,
// registered once per process at Go package init via
// [`lance_register_go_vtable`].
//
// `in_ptr` is logically `const`: the callee must never write through it. It
// is typed mutable only because cgo cannot express `const` parameters in
// exported Go function signatures.
typedef struct LanceGoVTable {
  // Must equal [`LANCE_GO_VTABLE_ABI_VERSION`].
  uint32_t abi_version;
  // Universal dispatch slot: invokes `method` on the Go plugin behind
  // `handle` with the `in_ptr`/`in_len` payload. On return, a non-NULL
  // `*out_ptr` is a `malloc`-allocated buffer of `*out_len` bytes that
  // the caller must release with `free`. Returns a `LANCE_GO_CALL_*`
  // code.
  int32_t (*invoke)(size_t handle,
                    int32_t method,
                    uint8_t *in_ptr,
                    size_t in_len,
                    uint8_t **out_ptr,
                    size_t *out_len);
  // Drops the Go-side registration for `handle`. Idempotent: releasing a
  // stale or unknown handle is a no-op.
  void (*release)(size_t handle);
} LanceGoVTable;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Returns the ABI version implemented by the linked native library.
uint32_t lance_abi_version(void);

// Returns a heap-allocated, NUL-terminated version string, e.g.
// `"lance-go-ffi 0.2.0 (lance 8.0.0)"`.
//
// The caller owns the returned pointer and must free it with
// `lance_string_free`.
char *lance_version(void);

// Takes blob-file handles for the selected rows of a blob column.
//
// - `spec_json`: JSON object `{"column": string, "row_ids"|"indices"|
//   "addresses": [uint]}` (exactly one selector). Must not be NULL.
// - `out`: receives an owning blob-list handle. Release it with
//   `lance_blob_list_close`.
//
// # Safety
//
// `ds` must be a valid dataset handle, `spec_json` a valid C string, and
// `out` valid for writes.
int32_t lance_dataset_take_blobs(const struct LanceDataset *ds,
                                 const char *spec_json,
                                 struct LanceBlobList **out);

// Returns the number of blob files in the list. NULL yields 0.
//
// # Safety
//
// `list` must be NULL or a valid blob-list handle.
size_t lance_blob_list_len(const struct LanceBlobList *list);

// Returns a *borrowed* pointer to the `i`-th blob file, valid until the list
// is closed. Returns NULL if `list` is NULL or `i` is out of range. Do NOT
// free the returned pointer. It is owned by the list.
//
// # Safety
//
// `list` must be NULL or a valid blob-list handle.
struct LanceBlobFile *lance_blob_list_get(const struct LanceBlobList *list, size_t i);

// Releases a blob list and every blob file it owns. NULL is a no-op. All blob
// pointers obtained from the list become invalid.
//
// # Safety
//
// `list` must be NULL or a handle from `lance_dataset_take_blobs` that has not
// already been closed.
void lance_blob_list_close(struct LanceBlobList *list);

// Reads the blob from its current cursor to the end and returns the bytes.
// Advances the cursor. On a fresh blob (cursor 0) this returns the whole
// blob. `*out_buf`/`*out_len` receive an owned buffer (NULL/0 when empty).
// Free it with `lance_bytes_free`.
//
// # Safety
//
// `bf` must be a valid blob handle, and `out_buf` and `out_len` valid for writes.
int32_t lance_blob_read(const struct LanceBlobFile *bf, uint8_t **out_buf, size_t *out_len);

// Reads `len` bytes starting at blob-local offset `start` (random access,
// does not move the cursor). `*out_buf`/`*out_len` receive an owned buffer
// (NULL/0 when empty). Free it with `lance_bytes_free`.
//
// # Safety
//
// `bf` must be a valid blob handle, and `out_buf` and `out_len` valid for writes.
int32_t lance_blob_read_range(const struct LanceBlobFile *bf,
                              uint64_t start,
                              uint64_t len,
                              uint8_t **out_buf,
                              size_t *out_len);

// Moves the blob's read cursor to `pos`.
//
// # Safety
//
// `bf` must be a valid blob handle.
int32_t lance_blob_seek(const struct LanceBlobFile *bf, uint64_t pos);

// Writes the blob's current cursor position into `out`.
//
// # Safety
//
// `bf` must be a valid blob handle and `out` valid for writes.
int32_t lance_blob_tell(const struct LanceBlobFile *bf, uint64_t *out);

// Returns the blob's total size in bytes. NULL yields 0.
//
// # Safety
//
// `bf` must be NULL or a valid blob handle.
uint64_t lance_blob_size(const struct LanceBlobFile *bf);

// Returns the blob's physical base offset within its data file. NULL yields 0.
//
// # Safety
//
// `bf` must be NULL or a valid blob handle.
uint64_t lance_blob_position(const struct LanceBlobFile *bf);

// Returns the blob's storage kind as its `BlobKind` discriminant
// (0 = inline, 1 = packed, 2 = dedicated, 3 = external). NULL yields 0.
//
// # Safety
//
// `bf` must be NULL or a valid blob handle.
uint8_t lance_blob_kind(const struct LanceBlobFile *bf);

// Writes the blob's URI into `*out_uri` as an owned C string, or NULL when the
// blob has no URI. The caller owns a non-NULL result and must free it with
// `lance_string_free`.
//
// # Safety
//
// `bf` must be a valid blob handle and `out_uri` valid for writes.
int32_t lance_blob_uri(const struct LanceBlobFile *bf, char **out_uri);

// Closes the underlying blob file early (releasing its I/O resources). The
// handle itself remains owned by the list and is freed by
// `lance_blob_list_close`. Further reads on a closed blob fail.
//
// # Safety
//
// `bf` must be a valid blob handle.
int32_t lance_blob_close(const struct LanceBlobFile *bf);

// Checks out the latest version of a branch as a NEW dataset handle. The
// original handle remains valid and unchanged.
//
// # Safety
//
// `ds` must be a valid handle, `branch` a valid C string, and `out` valid
// for writes.
int32_t lance_dataset_checkout_branch(const struct LanceDataset *ds,
                                      const char *branch,
                                      struct LanceDataset **out);

// Creates a branch pointing at the referenced version.
//
// - `branch`: new branch name. Must not be NULL.
// - `ref_json`: `{"version": uint}`, `{"tag": string}` or
//   `{"branch": string, "version"?: uint}`, or NULL for the version
//   currently checked out on `ds`.
// - `out`: if non-NULL, receives a handle to the new branch's dataset
//   (release with `lance_dataset_close`). Pass NULL to discard it.
//
// # Safety
//
// `ds` must be a valid handle, the strings NULL or valid C strings, and
// `out` NULL or valid for writes.
int32_t lance_dataset_create_branch(struct LanceDataset *ds,
                                    const char *branch,
                                    const char *ref_json,
                                    struct LanceDataset **out);

// Deletes a branch. With `force` set, the branch dataset is removed even if
// its metadata (`BranchContents`) is missing (zombie cleanup).
//
// # Safety
//
// `ds` must be a valid handle and `branch` a valid C string.
int32_t lance_dataset_delete_branch(struct LanceDataset *ds, const char *branch, bool force);

// Lists all branches of the dataset as a JSON object
// `{"<branch>": {"parentBranch": string|null, "parentVersion": uint,
// "createAt": uint, "manifestSize": uint, "metadata": {..}, ...}, ...}`.
// The caller owns `*out_json` and must free it with `lance_string_free`.
//
// # Safety
//
// `ds` must be a valid handle and `out_json` valid for writes.
int32_t lance_dataset_list_branches(const struct LanceDataset *ds, char **out_json);

// Shallow-clones the referenced version into a new dataset at `target_uri`
// (manifests are copied, data files stay in and are referenced from the
// source dataset).
//
// - `ref_json`: same contract as in `lance_dataset_create_branch` (NULL for
//   the currently checked-out version).
// - `storage_kv`: storage options for the TARGET, in the same format as
//   `lance_dataset_open`, or NULL.
// - `out`: receives a handle to the cloned dataset. Release it with
//   `lance_dataset_close`.
//
// # Safety
//
// `ds` must be a valid handle, strings NULL or valid C strings,
// `storage_kv` NULL or a valid NULL-terminated array, and `out` valid for
// writes.
int32_t lance_dataset_shallow_clone(struct LanceDataset *ds,
                                    const char *target_uri,
                                    const char *ref_json,
                                    const char *const *storage_kv,
                                    struct LanceDataset **out);

// Deep-clones the referenced version into a new dataset at `target_uri`
// (all data files are copied, and the clone is fully independent). Fails if a
// dataset already exists at the target.
//
// # Safety
//
// Same contracts as `lance_dataset_shallow_clone`.
int32_t lance_dataset_deep_clone(struct LanceDataset *ds,
                                 const char *target_uri,
                                 const char *ref_json,
                                 const char *const *storage_kv,
                                 struct LanceDataset **out);

// Appends a stream of record batches to the dataset the handle is
// currently checked out on, committing a new version. When the handle is
// checked out on a branch (e.g. from `lance_dataset_checkout_branch`), the
// append commits to that branch. The handle is advanced to the new
// version.
//
// - `stream`: Arrow C stream of record batches. Ownership is always taken,
//   even on error. Must not be NULL.
//
// # Safety
//
// `ds` must be a valid handle and `stream` a valid, unmoved Arrow C
// stream.
int32_t lance_dataset_append(struct LanceDataset *ds, struct ArrowArrayStream *stream);

// Lists all tags ordered by the version they point at as a JSON array
// `[{"name": string, "branch": string|null, "version": uint,
// "manifestSize": uint, "metadata": {..}, ...}, ...]`. Descending version
// order by default. Set `ascending` for oldest-first. Ties are broken by
// tag name. The caller owns `*out_json` and must free it with
// `lance_string_free`.
//
// # Safety
//
// `ds` must be a valid handle and `out_json` valid for writes.
int32_t lance_dataset_tag_list_ordered(const struct LanceDataset *ds,
                                       bool ascending,
                                       char **out_json);

// Replaces the metadata key-value map attached to a tag. The tag must
// exist.
//
// - `metadata_json`: JSON object `{"key": "value", ...}` (the new complete
//   metadata map). Must not be NULL.
//
// # Safety
//
// `ds` must be a valid handle and the strings valid C strings.
int32_t lance_dataset_tag_replace_metadata(const struct LanceDataset *ds,
                                           const char *tag,
                                           const char *metadata_json);

// Returns a clone of the dataset wrapped so that immutable file reads are
// served through the Go `ObjectStoreCache` behind `plugin_handle`. `out`
// receives a NEW dataset handle. The caller should close the original.
//
// # Safety
//
// `ds` must be a valid dataset handle, `plugin_handle` a live Go plugin
// handle, and `out` valid for writes.
int32_t lance_dataset_wrap_object_store_cache(const struct LanceDataset *ds,
                                              size_t plugin_handle,
                                              struct LanceDataset **out);

// Registers the process-wide Go callback vtable. Called exactly once from
// the Go package init. The struct is copied, so the pointer only needs to
// stay valid for the duration of the call.
//
// Errors: `InvalidArgument` for a NULL vtable, an `abi_version` mismatch,
// or NULL function-pointer slots. `AlreadyExists` if a vtable has already
// been registered in this process.
//
// # Safety
//
// `vtable` must be NULL or point to a valid, initialized `LanceGoVTable`
// whose function pointers remain valid for the process lifetime (cgo
// export trampolines are).
int32_t lance_register_go_vtable(const struct LanceGoVTable *vtable);

// Test-only: drives [`GoPlugin::call`] synchronously so the Go test suite
// can exercise the full Go → Rust → Go loop. On success `*out_ptr` /
// `*out_len` receive a `malloc`-allocated copy of the plugin response
// (NULL/0 for an empty response) that the caller must release with `free`.
// A plugin miss maps to `ErrorCode::NotFound`, and a plugin error maps to
// `ErrorCode::Internal` with the plugin's message.
//
// # Safety
//
// `payload` must be NULL or point at `payload_len` readable bytes, and
// `out_ptr` and `out_len` must be valid writable pointers.
int32_t lance_test_callback_roundtrip(size_t handle,
                                      int32_t method,
                                      const uint8_t *payload,
                                      size_t payload_len,
                                      uint8_t **out_ptr,
                                      size_t *out_len);

// Test-only: like [`lance_test_callback_roundtrip`] but through
// [`GoPlugin::call_blocking`] on the shared tokio runtime
// (`block_on(spawn_blocking(...))`), the path async plugin bindings use.
//
// # Safety
//
// Same contract as [`lance_test_callback_roundtrip`].
int32_t lance_test_callback_roundtrip_async(size_t handle,
                                            int32_t method,
                                            const uint8_t *payload,
                                            size_t payload_len,
                                            uint8_t **out_ptr,
                                            size_t *out_len);

// Test-only: releases a Go plugin handle through the vtable's `release`
// slot, exercising [`GoPlugin::release`] from native code.
//
// # Safety
//
// Callable from any thread. `handle` may be stale (release is idempotent
// on the Go side).
void lance_test_callback_release(size_t handle);

// Returns the dataset config (from the manifest) as a JSON object
// `{"key": "value", ...}`. The caller owns `*out_json` and must free it
// with `lance_string_free`.
//
// # Safety
//
// `ds` must be a valid handle and `out_json` valid for writes.
int32_t lance_dataset_config(const struct LanceDataset *ds, char **out_json);

// Returns the table metadata as a JSON object. The caller owns `*out_json`
// and must free it with `lance_string_free`.
//
// # Safety
//
// `ds` must be a valid handle and `out_json` valid for writes.
int32_t lance_dataset_metadata(const struct LanceDataset *ds, char **out_json);

// Updates the dataset config, committing a new version.
//
// - `updates_json`: JSON object `{"key": "value"|null, ...}`. A null value
//   removes the key. Must not be NULL.
// - `replace`: when true the entire config map is replaced by the updates
//   instead of merged.
// - `out_json`: if non-NULL, receives the post-update config map as JSON
//   (free with `lance_string_free`).
//
// # Safety
//
// `ds` must be a valid handle, `updates_json` a valid C string, and
// `out_json` NULL or valid for writes.
int32_t lance_dataset_update_config(struct LanceDataset *ds,
                                    const char *updates_json,
                                    bool replace,
                                    char **out_json);

// Updates the table metadata. Same contract as
// `lance_dataset_update_config`.
//
// # Safety
//
// Same contracts as `lance_dataset_update_config`.
int32_t lance_dataset_update_metadata(struct LanceDataset *ds,
                                      const char *updates_json,
                                      bool replace,
                                      char **out_json);

// Updates the schema metadata. Same contract as
// `lance_dataset_update_config`.
//
// # Safety
//
// Same contracts as `lance_dataset_update_config`.
int32_t lance_dataset_update_schema_metadata(struct LanceDataset *ds,
                                             const char *updates_json,
                                             bool replace,
                                             char **out_json);

// Deletes keys from the dataset config, committing a new version.
//
// - `keys_json`: JSON array of key names, e.g. `["a", "b"]`. Must not be
//   NULL. Deleting a key that does not exist is a no-op.
//
// # Safety
//
// `ds` must be a valid handle and `keys_json` a valid C string.
int32_t lance_dataset_delete_config_keys(struct LanceDataset *ds, const char *keys_json);

// Returns the initial storage options this dataset handle was opened with as
// a JSON object `{"key": "value", ...}` (an empty object when none were
// given). The caller owns `*out_json` and must free it with
// `lance_string_free`.
//
// # Safety
//
// `ds` must be a valid handle and `out_json` valid for writes.
int32_t lance_dataset_storage_options(const struct LanceDataset *ds, char **out_json);

// Updates the metadata of a single field, committing a new version.
//
// - `field`: field name (nested fields use dotted paths). Must not be NULL.
// - `updates_json`: JSON object `{"key": "value"|null, ...}`. A null value
//   removes the key. Must not be NULL.
// - `replace`: when true the field's metadata map is replaced instead of
//   merged.
//
// # Safety
//
// `ds` must be a valid handle and the strings valid C strings.
int32_t lance_dataset_update_field_metadata(struct LanceDataset *ds,
                                            const char *field,
                                            const char *updates_json,
                                            bool replace);

// Deletes all rows from the dataset (committing a new version).
//
// # Safety
//
// `ds` must be a valid handle.
int32_t lance_dataset_truncate(struct LanceDataset *ds);

// Counts the soft-deleted rows still present in the dataset's files.
//
// # Safety
//
// `ds` must be a valid handle and `out` valid for writes.
int32_t lance_dataset_count_deleted_rows(const struct LanceDataset *ds, uint64_t *out);

// Reports whether the dataset has a newer committed version than the one
// checked out on this handle.
//
// # Safety
//
// `ds` must be a valid handle and `out` valid for writes.
int32_t lance_dataset_is_stale(const struct LanceDataset *ds, bool *out);

// Reports whether the immediate successor version's manifest exists (a fast
// contiguous-history probe, prefer `lance_dataset_is_stale` for a general
// freshness check).
//
// # Safety
//
// `ds` must be a valid handle and `out` valid for writes.
int32_t lance_dataset_has_successor_version(const struct LanceDataset *ds, bool *out);

// Validates the dataset's internal consistency (fragment ids, field ids,
// physical rows).
//
// # Safety
//
// `ds` must be a valid handle.
int32_t lance_dataset_validate(const struct LanceDataset *ds);

// Migrates the dataset's manifest naming scheme to V2 (constant-time
// latest-manifest lookups on object storage). The handle is re-pointed at
// the migrated latest version. This call is deliberately NOT cancellable:
// once started it runs to completion regardless of the caller's
// cancellation token, because an aborted migration would leave a mix of V1
// and V2 manifest names that Lance refuses to open.
//
// # Safety
//
// `ds` must be a valid handle.
int32_t lance_dataset_migrate_manifest_paths_v2(struct LanceDataset *ds);

// Counts data files with fewer rows than `max_rows_per_group` (candidates
// for compaction).
//
// # Safety
//
// `ds` must be a valid handle and `out` valid for writes.
int32_t lance_dataset_num_small_files(const struct LanceDataset *ds,
                                      uint64_t max_rows_per_group,
                                      uint64_t *out);

// Returns session-cache statistics as JSON `{"cache_size_bytes": uint,
// "index_cache_entry_count": uint, "index_cache_hit_rate": float}`. The
// caller owns `*out_json` and must free it with `lance_string_free`.
//
// # Safety
//
// `ds` must be a valid handle and `out_json` valid for writes.
int32_t lance_dataset_cache_stats(const struct LanceDataset *ds, char **out_json);

// Returns the dataset's storage locations as JSON `{"uri": string,
// "base": string, "data_dir": string, "indices_dir": string,
// "versions_dir": string, "branch": string|null}`. `base` and the `*_dir`
// values are object-store paths (no scheme), and `uri` is fully qualified. The
// caller owns `*out_json` and must free it with `lance_string_free`.
//
// # Safety
//
// `ds` must be a valid handle and `out_json` valid for writes.
int32_t lance_dataset_paths(const struct LanceDataset *ds, char **out_json);

// Removes old dataset versions according to a cleanup policy.
//
// - `policy_json`: optional JSON object
//   `{"before_timestamp"?: rfc3339, "before_version"?: uint,
//   "delete_unverified"?: bool, "error_if_tagged_old_versions"?: bool
//   (default true), "clean_referenced_branches"?: bool,
//   "delete_rate_limit"?: uint}`, or NULL for the default policy.
// - `out_json`: receives the removal statistics as JSON (same shape as
//   `lance_dataset_cleanup_old_versions`). Free with `lance_string_free`.
//
// # Safety
//
// `ds` must be a valid handle, `policy_json` NULL or a valid C string, and
// `out_json` valid for writes.
int32_t lance_dataset_cleanup_with_policy(const struct LanceDataset *ds,
                                          const char *policy_json,
                                          char **out_json);

// Computes per-field storage statistics as JSON
// `{"fields": [{"id": uint, "bytes_on_disk": uint}, ...]}`. The caller owns
// `*out_json` and must free it with `lance_string_free`.
//
// # Safety
//
// `ds` must be a valid handle and `out_json` valid for writes.
int32_t lance_dataset_data_stats(const struct LanceDataset *ds, char **out_json);

// Registers additional storage base paths in the dataset manifest
// (committing a new version). The handle is updated to the new version.
//
// - `bases_json`: JSON array `[{"id": uint (non-zero), "name"?: string,
//   "is_dataset_root"?: bool, "path": string}, ...]`. Must not be NULL.
// - `properties_json`: optional JSON object of transaction properties, or
//   NULL.
//
// # Safety
//
// `ds` must be a valid handle and the strings valid C strings.
int32_t lance_dataset_add_bases(struct LanceDataset *ds,
                                const char *bases_json,
                                const char *properties_json);

// Opens an existing Lance dataset.
//
// - `uri`: dataset URI (e.g. a local path). Must not be NULL.
// - `storage_kv`: NULL-terminated array of alternating storage-option
//   keys/values (`[k1, v1, ..., NULL]`), or NULL for none.
// - `options_json`: optional JSON object
//   `{"version"?: uint, "tag"?: string, "branch"?: string,
//   "index_cache_bytes"?: uint, "metadata_cache_bytes"?: uint}`, or NULL.
//   `branch` checks out the named branch (at `version` if also given,
//   otherwise its latest version).
// - `out`: receives the dataset handle on success. Release it with
//   `lance_dataset_close`.
//
// # Safety
//
// All pointer arguments must satisfy the contracts above and `out` must be
// valid for writes.
int32_t lance_dataset_open(const char *uri,
                           const char *const *storage_kv,
                           const char *options_json,
                           struct LanceDataset **out);

// Writes an Arrow stream of record batches to a Lance dataset.
//
// - `stream`: Arrow C stream of record batches. Ownership is always taken,
//   even on error, so the producer is released exactly once. Must not be
//   NULL.
// - `uri`: destination dataset URI. Must not be NULL.
// - `options_json`: optional JSON object
//   `{"mode"?: "create"|"append"|"overwrite", "max_rows_per_file"?: uint,
//   "max_rows_per_group"?: uint, "max_bytes_per_file"?: uint,
//   "data_storage_version"?: string, "enable_stable_row_ids"?: bool,
//   "enable_v2_manifest_paths"?: bool,
//   "auto_cleanup"?: {"interval": uint, "older_than_seconds": int},
//   "skip_auto_cleanup"?: bool, "transaction_properties"?: {..},
//   "external_blob_mode"?: "reference"|"ingest",
//   "blob_pack_file_size_threshold"?: uint,
//   "allow_external_blob_outside_bases"?: bool,
//   "initial_bases"?: [{"id": uint, "name"?: string,
//   "is_dataset_root"?: bool, "path": string}],
//   "target_bases"?: [uint], "target_base_names_or_paths"?: [string],
//   "base_store_params"?: {"<base>": {"<key>": "<value>"}}}`,
//   or NULL (defaults to mode "create").
// - `storage_kv`: same format as in `lance_dataset_open`, or NULL.
// - `out`: if non-NULL, receives a handle to the resulting dataset (release
//   with `lance_dataset_close`). Pass NULL to discard it.
//
// # Safety
//
// All pointer arguments must satisfy the contracts above.
int32_t lance_dataset_write(struct ArrowArrayStream *stream,
                            const char *uri,
                            const char *options_json,
                            const char *const *storage_kv,
                            struct LanceDataset **out);

// Releases a dataset handle. NULL is a no-op. The handle must not be used
// again afterwards.
//
// # Safety
//
// `ds` must be NULL or a handle obtained from `lance_dataset_open` /
// `lance_dataset_write` that has not already been closed.
void lance_dataset_close(struct LanceDataset *ds);

// Counts the rows in the dataset, optionally restricted by an SQL filter
// expression (`filter` may be NULL for "count everything").
//
// # Safety
//
// `ds` must be a valid handle, `filter` NULL or a valid C string, and `out`
// valid for writes.
int32_t lance_dataset_count_rows(const struct LanceDataset *ds, const char *filter, uint64_t *out);

// Exports the dataset schema into `out` as an Arrow C schema. The caller
// owns the result and must call its `release` callback.
//
// # Safety
//
// `ds` must be a valid handle and `out` valid for writes.
int32_t lance_dataset_schema(const struct LanceDataset *ds, struct ArrowSchema *out);

// Returns the currently checked-out version of the dataset as a JSON string
// `{"version": uint, "timestamp": string, "metadata": {..}}`. The caller
// owns `*out_json` and must free it with `lance_string_free`.
//
// # Safety
//
// `ds` must be a valid handle and `out_json` valid for writes.
int32_t lance_dataset_version(const struct LanceDataset *ds, char **out_json);

// Returns the latest committed version id of the dataset (which may be newer
// than the checked-out version).
//
// # Safety
//
// `ds` must be a valid handle and `out` valid for writes.
int32_t lance_dataset_latest_version(const struct LanceDataset *ds, uint64_t *out);

// Streams the rows changed between two dataset versions.
//
// - `spec_json`: optional JSON object with exactly one of
//   `{"compared_against_version": uint}`, `{"begin_version": uint,
//   "end_version": uint}` or `{"begin_date": rfc3339, "end_date": rfc3339}`
//   (begin exclusive, end inclusive), or NULL/empty (rejected by lance:
//   a range must be specified).
// - `kind`: 0 = inserted rows, 1 = updated rows, 2 = upserted rows
//   (inserted + updated).
// - `out`: receives a self-contained Arrow C stream of the changed rows
//   (including the `_rowid`, `_row_created_at_version` and
//   `_row_last_updated_at_version` columns). The caller owns it and must
//   call its `release` callback.
//
// # Safety
//
// `ds` must be a valid handle, `spec_json` NULL or a valid C string, and
// `out` valid for writes (previous contents are overwritten without
// release).
int32_t lance_dataset_delta(const struct LanceDataset *ds,
                            const char *spec_json,
                            int32_t kind,
                            struct ArrowArrayStream *out);

// Lists the transactions between two dataset versions as JSON
// `[{"read_version": uint, "uuid": string, "operation": string,
// "tag": string|null, "properties": {..}|null}, ...]`. The caller owns
// `*out_json` and must free it with `lance_string_free`.
//
// - `spec_json`: same contract as in `lance_dataset_delta`.
//
// # Safety
//
// `ds` must be a valid handle, `spec_json` NULL or a valid C string, and
// `out_json` valid for writes.
int32_t lance_dataset_delta_transactions(const struct LanceDataset *ds,
                                         const char *spec_json,
                                         char **out_json);

// Builds an *uncommitted* index segment over an optional fragment subset and
// returns it as protobuf bytes (`out_pb`/`out_pb_len`, freed with
// `lance_bytes_free`) plus a JSON summary (`out_json`).
//
// - `columns`: NULL-terminated array of column names (exactly one).
// - `index_type`: same string contract as `lance_dataset_create_index_v2`.
// - `params_json`: same shape as `lance_dataset_create_index_v2`.
// - `options_json`: `{"train"?, "fragments"?: [uint], "index_uuid"?: string,
//   "name"?: string, "transaction_properties"?: {string: string}}`.
// - `centroids`/`codebook` (+ schemas): optional shared training arrays,
//   same ownership contract as `lance_dataset_create_index_v2`.
// - `preprocessed_stream`: optional preprocessed-data Arrow stream (BTree).
//   NULL for none. Ownership is always taken when non-NULL.
//
// # Safety
//
// All pointer arguments must satisfy the contracts above.
int32_t lance_dataset_create_index_uncommitted(struct LanceDataset *ds,
                                               const char *const *columns,
                                               const char *index_type,
                                               const char *params_json,
                                               const char *options_json,
                                               struct ArrowArray *centroids,
                                               struct ArrowSchema *centroids_schema,
                                               struct ArrowArray *codebook,
                                               struct ArrowSchema *codebook_schema,
                                               struct ArrowArrayStream *preprocessed_stream,
                                               uint8_t **out_pb,
                                               size_t *out_pb_len,
                                               char **out_json);

// Merges uncommitted index segments (each `pb::IndexMetadata` bytes) into a
// single uncommitted segment, returned as protobuf bytes + JSON summary.
//
// # Safety
//
// The two arrays must each hold `num_segments` valid entries, and `segments_pb[i]`
// must point to `segments_pb_lens[i]` valid bytes.
int32_t lance_dataset_merge_index_segments(const struct LanceDataset *ds,
                                           const uint8_t *const *segments_pb,
                                           const size_t *segments_pb_lens,
                                           size_t num_segments,
                                           uint8_t **out_pb,
                                           size_t *out_pb_len,
                                           char **out_json);

// Commits one or more physical index segments (each `pb::IndexMetadata`
// bytes) as a single logical index named `index_name` over `column`, and
// updates the dataset handle to the resulting version. Returns the new
// version as JSON `{"version": uint}`.
//
// # Safety
//
// Pointer contracts as on `lance_dataset_merge_index_segments`. `name` and
// `column` must be valid C strings.
int32_t lance_dataset_commit_index_segments(struct LanceDataset *ds,
                                            const char *index_name,
                                            const char *column,
                                            const uint8_t *const *segments_pb,
                                            const size_t *segments_pb_lens,
                                            size_t num_segments,
                                            char **out_json);

// Streams the rows of an index partition into the caller-provided
// `ArrowArrayStream`. The partition is materialized before export (partitions
// are small). The caller owns the exported stream.
//
// # Safety
//
// `ds` must be a valid handle, `name` a valid C string, and `out` valid for
// writes (previous contents overwritten without release).
int32_t lance_dataset_read_index_partition(const struct LanceDataset *ds,
                                           const char *name,
                                           uint64_t partition,
                                           bool with_vector,
                                           struct ArrowArrayStream *out);

// Plans a compaction and returns the plan as JSON (the plan's task list is
// `serde`-serializable, unlike transactions). This is the planning half of a
// distributed compaction. Executing tasks and committing their results are
// deferred (see the module note and the wrap-up report).
//
// # Safety
//
// `ds` must be a valid handle and `out_json` valid for writes.
int32_t lance_dataset_plan_compaction(const struct LanceDataset *ds,
                                      const char *options_json,
                                      char **out_json);

// Returns the error code recorded by the most recent failing `lance_*` call
// on the calling thread, or `0` (Ok) if none.
int32_t lance_last_error_code(void);

// Returns the message for the calling thread's last error, or NULL if none.
//
// The pointer is borrowed: it stays valid until the next error recorded on
// the same thread. Do NOT pass it to `lance_string_free`.
const char *lance_last_error_message(void);

// Frees a string previously returned as an owned `*mut c_char` by this
// library (e.g. `lance_version`). NULL is a no-op.
//
// # Safety
//
// `s` must be NULL or a pointer obtained from an owned-string-returning
// function of this library, and must not be used (or freed) again afterwards.
void lance_string_free(char *s);

// Adds new columns to the dataset, committing a new version.
//
// - `spec_json`: JSON object selecting the transform. One of
//   `{"kind": "sql", "expressions": [["name", "sql expr"], ...],
//   "read_columns"?: [string], "batch_size"?: uint}`,
//   `{"kind": "reader", "batch_size"?: uint}` (requires `stream`), or
//   `{"kind": "all_nulls"}` (requires `schema`). Must not be NULL.
// - `stream`: Arrow C stream providing the new columns' values for
//   `kind = "reader"`, NULL otherwise. Ownership is always taken when
//   non-NULL, even on error, so the producer is released exactly once.
// - `schema`: Arrow C schema describing the new all-null columns for
//   `kind = "all_nulls"`, NULL otherwise. Ownership is always taken when
//   non-NULL, even on error.
//
// # Safety
//
// `ds` must be a valid handle and the other arguments must satisfy the
// contracts above.
int32_t lance_dataset_add_columns(struct LanceDataset *ds,
                                  const char *spec_json,
                                  struct ArrowArrayStream *stream,
                                  struct ArrowSchema *schema);

// Drops columns from the dataset, committing a new version. This is a
// metadata-only operation. The column data is removed later by compaction
// and cleanup.
//
// - `columns`: NULL-terminated array of column names (`[c1, c2, NULL]`).
//   Must contain at least one column.
//
// # Safety
//
// `ds` must be a valid handle and `columns` a valid NULL-terminated array
// of valid C strings.
int32_t lance_dataset_drop_columns(struct LanceDataset *ds, const char *const *columns);

// Alters columns of the dataset (rename, nullability, type cast),
// committing a new version.
//
// - `alterations_json`: JSON array
//   `[{"path": string, "rename"?: string, "nullable"?: bool,
//   "data_type"?: string}, ...]`. `data_type` accepts: int32, int64,
//   float32, float64, utf8, large_utf8, binary, bool, date32, date64,
//   timestamp_us, timestamp_ns. Must not be NULL or empty.
//
// # Safety
//
// `ds` must be a valid handle and `alterations_json` a valid C string.
int32_t lance_dataset_alter_columns(struct LanceDataset *ds, const char *alterations_json);

// Merges new columns into the dataset by joining an Arrow stream on a key
// column, committing a new version. Rows without a match get nulls.
//
// - `stream`: Arrow C stream with the right-hand side of the join.
//   Ownership is always taken, even on error, so the producer is released
//   exactly once. Must not be NULL.
// - `left_on` / `right_on`: join key column names in the dataset and the
//   stream, respectively. Must not be NULL.
//
// # Safety
//
// `ds` must be a valid handle and the other arguments must satisfy the
// contracts above.
int32_t lance_dataset_merge(struct LanceDataset *ds,
                            struct ArrowArrayStream *stream,
                            const char *left_on,
                            const char *right_on);

// Lists the dataset's fragments as a JSON array of objects
// `{"id": uint, "num_rows": uint, "physical_rows": uint,
// "num_deletions": uint, "num_data_files": uint, "data_files": [string]}`.
// `num_rows` is the live row count. The caller owns `*out_json` and must
// free it with `lance_string_free`.
//
// # Safety
//
// `ds` must be a valid dataset handle and `out_json` valid for writes.
int32_t lance_dataset_fragments(const struct LanceDataset *ds, char **out_json);

// Opens fragment `frag_id` as an opaque handle. Fails with `NotFound` when no
// fragment has that id.
//
// # Safety
//
// `ds` must be a valid dataset handle and `out` valid for writes.
int32_t lance_dataset_get_fragment(const struct LanceDataset *ds,
                                   uint32_t frag_id,
                                   struct LanceFragment **out);

// Releases a fragment handle. NULL is a no-op. Streams previously exported
// from this fragment remain valid.
//
// # Safety
//
// `f` must be NULL or a handle from `lance_dataset_get_fragment` that has not
// already been closed.
void lance_fragment_close(struct LanceFragment *f);

// Counts the live rows in the fragment, optionally restricted by an SQL
// `filter` (NULL for "count everything").
//
// # Safety
//
// `f` must be a valid fragment handle, `filter` NULL or a valid C string, and
// `out` valid for writes.
int32_t lance_fragment_count_rows(const struct LanceFragment *f, const char *filter, uint64_t *out);

// Counts the rows deleted from the fragment.
//
// # Safety
//
// `f` must be a valid fragment handle and `out` valid for writes.
int32_t lance_fragment_count_deletions(const struct LanceFragment *f, uint64_t *out);

// Returns the number of physical rows stored in the fragment (before
// deletions).
//
// # Safety
//
// `f` must be a valid fragment handle and `out` valid for writes.
int32_t lance_fragment_physical_rows(const struct LanceFragment *f, uint64_t *out);

// Returns the fragment's metadata as a JSON object (the serde form of
// Lance's `Fragment`: `{"id": uint, "files": [{"path": string, ...}],
// "physical_rows": uint|null, "deletion_file"?: {..}, ...}`). The caller owns
// `*out_json` and must free it with `lance_string_free`.
//
// # Safety
//
// `f` must be a valid fragment handle and `out_json` valid for writes.
int32_t lance_fragment_metadata(const struct LanceFragment *f, char **out_json);

// Takes rows from the fragment by in-fragment offset and returns them as a
// one-batch Arrow C stream.
//
// - `spec_json`: JSON object `{"indices": [uint], "columns"?: [string]}`.
//   Must not be NULL.
// - `out`: receives a self-contained one-batch Arrow C stream. The caller
//   owns it and must call its `release` callback.
//
// # Safety
//
// `f` must be a valid fragment handle, `spec_json` a valid C string, and
// `out` valid for writes (previous contents overwritten without release).
int32_t lance_fragment_take(const struct LanceFragment *f,
                            const char *spec_json,
                            struct ArrowArrayStream *out);

// Scans the fragment and exports the result as a self-contained Arrow C
// stream. Self-contained (no scanner.rs cross-module edit): builds a
// `Scanner` from the fragment and applies a documented subset of scan
// options inline.
//
// - `scan_json`: optional JSON object `{"columns"?: [string],
//   "filter"?: string, "limit"?: int, "offset"?: int, "with_row_id"?: bool,
//   "with_row_address"?: bool, "batch_size"?: uint, "scan_in_order"?: bool}`,
//   or NULL for a full fragment scan. Unknown fields are rejected.
// - `out`: receives a self-contained Arrow C stream. The caller owns it and
//   must call its `release` callback. It stays valid after the fragment and
//   dataset handles are closed.
//
// # Safety
//
// `f` must be a valid fragment handle, `scan_json` NULL or a valid C string,
// and `out` valid for writes (previous contents overwritten without release).
int32_t lance_fragment_scan_to_stream(const struct LanceFragment *f,
                                      const char *scan_json,
                                      struct ArrowArrayStream *out);

// Adds columns computed by a Go batch-UDF, committing a new version.
//
// - `ds`: dataset handle, updated in place to the new version.
// - `output_schema`: Arrow C schema of the new columns (ownership taken).
// - `udf_plugin_handle`: Go mapper plugin handle.
// - `options_json`: `{"read_columns"?: [string]}` or NULL.
// - `batch_size`: rows per UDF batch (0 = default).
// - `checkpoint_plugin_handle`: Go checkpoint-store plugin handle (0 = none).
//
// # Safety
//
// `ds` must be a valid handle, `output_schema` a valid unmoved Arrow C schema
// (always consumed), and the plugin handles live (or 0 for the checkpoint).
int32_t lance_dataset_add_columns_udf(struct LanceDataset *ds,
                                      struct ArrowSchema *output_schema,
                                      size_t udf_plugin_handle,
                                      const char *options_json,
                                      uint32_t batch_size,
                                      size_t checkpoint_plugin_handle);

// Creates an index on `columns` of the dataset. Upon success a new dataset
// version is committed and the handle is updated to it.
//
// - `columns`: NULL-terminated array of column names (currently Lance
//   supports exactly one column per index). Must not be NULL.
// - `index_type`: an `IndexType` discriminant: BTree=1, Bitmap=2,
//   LabelList=3, Inverted=4, NGram=5, ZoneMap=8, BloomFilter=9,
//   IvfFlat=101, IvfSq=102, IvfPq=103, IvfHnswSq=104, IvfHnswPq=105,
//   IvfHnswFlat=106, IvfRq=107.
// - `name`: optional index name, or NULL for the Lance default
//   (`<column>_idx`).
// - `params_json`: optional JSON parameter document, or NULL for defaults.
//   Shape depends on the index family:
//   - scalar types: `{"params"?: <index-specific JSON>}`
//   - inverted: `{"base_tokenizer"?: string, "language"?: string,
//     "with_position"?: bool, "lower_case"?: bool, "stem"?: bool,
//     "remove_stop_words"?: bool, "ascii_folding"?: bool,
//     "max_token_length"?: uint (0 = unlimited),
//     "custom_stop_words"?: [string], "ngram_min_length"?: uint,
//     "ngram_max_length"?: uint, "ngram_prefix_only"?: bool}`
//   - vector types: `{"metric"?: "l2"|"cosine"|"dot"|"hamming",
//     "num_partitions"?: uint, "num_bits"?: uint,
//     "num_sub_vectors"?: uint, "max_iterations"?: uint,
//     "sample_rate"?: uint, "rotation_type"?: "fast"|"matrix",
//     "hnsw"?: {"m"?: uint, "ef_construction"?: uint, "max_level"?: uint}}`
// - `replace`: whether an existing index with the same name is replaced
//   (false makes the call fail if the name is taken).
// - `out_json`: if non-NULL, receives the created index metadata as JSON
//   `{"name", "uuid", "fields", "dataset_version", "index_version",
//   "created_at"?}`. Free with `lance_string_free`.
//
// # Safety
//
// All pointer arguments must satisfy the contracts above.
int32_t lance_dataset_create_index(struct LanceDataset *ds,
                                   const char *const *columns,
                                   int32_t index_type,
                                   const char *name,
                                   const char *params_json,
                                   bool replace,
                                   char **out_json);

// Creates an index on `columns` of the dataset, selecting the index type by
// string. Upon success a new dataset version is committed and the handle is
// updated to it.
//
// This is the v2 form of `lance_dataset_create_index`. It additionally
// supports scalar index plugins and Arrow-passed training data.
//
// - `columns`: NULL-terminated array of column names (currently Lance
//   supports exactly one column per index). Must not be NULL.
// - `index_type`: the index type, case-insensitive. One of the builtin
//   names `"btree"`, `"bitmap"`, `"labellist"`, `"inverted"`, `"ngram"`,
//   `"zonemap"`, `"bloomfilter"`, `"rtree"`, `"fm"`, `"ivf_flat"`,
//   `"ivf_sq"`, `"ivf_pq"`, `"ivf_rq"`, `"ivf_hnsw_flat"`, `"ivf_hnsw_pq"`,
//   `"ivf_hnsw_sq"`, or a scalar index plugin name, optionally prefixed
//   with `"scalar:"` (e.g. `"json"` or `"scalar:json"`), routed through the
//   scalar index plugin registry.
// - `name`: optional index name, or NULL for the Lance default.
// - `params_json`: optional JSON parameter document, or NULL for defaults.
//   Shape depends on the index family:
//   - scalar builtin and plugin types: `{"params"?: <index-specific JSON>}`
//     (e.g. for the "json" plugin:
//     `{"params": {"target_index_type": "btree",
//     "target_index_parameters"?: "<JSON string>", "path": "x"}}`)
//   - inverted: same shape as `lance_dataset_create_index`
//   - vector types: the `lance_dataset_create_index` shape plus
//     `"target_partition_size"?: uint, "retrain"?: bool,
//     "streaming_sample_rate"?: uint, "streaming_coreset_rate"?: uint,
//     "streaming_refine_passes"?: uint, "shuffle_partition_batches"?: uint,
//     "shuffle_partition_concurrency"?: uint,
//     "precomputed_partitions_file"?: string,
//     "storage_options"?: {string: string}, "kmeans_redos"?: uint,
//     "hnsw"?: {..., "prefetch_distance"?: uint},
//     "index_file_version"?: "legacy"|"v3", "skip_transpose"?: bool,
//     "runtime_hints"?: {string: string}`
// - `centroids` / `centroids_schema`: optional Arrow C Data Interface
//   FixedSizeList array of pre-computed IVF centroids (vector types only).
//   Both NULL or both non-NULL. Ownership of both structs is always taken,
//   even on error.
// - `codebook` / `codebook_schema`: optional Arrow C Data Interface array
//   holding a pre-computed PQ codebook (PQ types only). Same ownership
//   contract as `centroids`.
// - `replace`: whether an existing index with the same name is replaced.
// - `out_json`: if non-NULL, receives the created index metadata as JSON
//   (same shape as `lance_dataset_create_index`). Free with
//   `lance_string_free`.
//
// # Safety
//
// All pointer arguments must satisfy the contracts above.
int32_t lance_dataset_create_index_v2(struct LanceDataset *ds,
                                      const char *const *columns,
                                      const char *index_type,
                                      const char *name,
                                      const char *params_json,
                                      struct ArrowArray *centroids,
                                      struct ArrowSchema *centroids_schema,
                                      struct ArrowArray *codebook,
                                      struct ArrowSchema *codebook_schema,
                                      bool replace,
                                      char **out_json);

// Lists the indices of the dataset as a JSON array of
// `{"name", "uuid", "fields", "dataset_version", "index_version",
// "created_at"?}` objects. The caller owns `*out_json` and must free it
// with `lance_string_free`.
//
// # Safety
//
// `ds` must be a valid handle and `out_json` valid for writes.
int32_t lance_dataset_list_indices(const struct LanceDataset *ds, char **out_json);

// Returns index statistics (a Lance-defined JSON document) for the index
// named `name`. The caller owns `*out_json` and must free it with
// `lance_string_free`.
//
// # Safety
//
// `ds` must be a valid handle, `name` a valid C string, and `out_json`
// valid for writes.
int32_t lance_dataset_index_statistics(const struct LanceDataset *ds,
                                       const char *name,
                                       char **out_json);

// Drops the index named `name`. Upon success a new dataset version is
// committed and the handle is updated to it.
//
// # Safety
//
// `ds` must be a valid handle and `name` a valid C string.
int32_t lance_dataset_drop_index(struct LanceDataset *ds, const char *name);

// Optimizes (merges/updates) the dataset's indices to cover newly written
// data. Upon success a new dataset version is committed and the handle is
// updated to it.
//
// - `options_json`: optional JSON object `{"num_indices_to_merge"?: uint,
//   "index_names"?: [string], "retrain"?: bool,
//   "transaction_properties"?: {string: string}}`, or NULL for the Lance
//   defaults (merge into 1 index, all indices, no retrain).
//
// # Safety
//
// `ds` must be a valid handle and `options_json` NULL or a valid C string.
int32_t lance_dataset_optimize_indices(struct LanceDataset *ds, const char *options_json);

// Loads the index named `name` into memory ahead of queries.
//
// # Safety
//
// `ds` must be a valid handle and `name` a valid C string.
int32_t lance_dataset_prewarm_index(const struct LanceDataset *ds, const char *name);

// Loads the index named `name` into memory ahead of queries, with
// index-type-specific options.
//
// - `options_json`: JSON object selecting the options variant. Currently
//   the only variant is FTS (inverted indices):
//   `{"fts": {"with_position"?: bool}}`. `with_position` additionally
//   prewarms token positions along with the posting lists.
//
// # Safety
//
// `ds` must be a valid handle, `name` a valid C string, and `options_json`
// NULL or a valid C string.
int32_t lance_dataset_prewarm_index_with_options(const struct LanceDataset *ds,
                                                 const char *name,
                                                 const char *options_json);

// Describes the dataset's indices as a JSON array of
// `{"name", "index_type", "type_url", "rows_indexed", "field_ids",
// "details"?, "total_size_bytes"?, "segments": [...]}` objects, where
// `"segments"` entries have the `lance_dataset_list_indices` shape and
// `"details"` is an index-type-specific JSON document (omitted when it
// cannot be decoded). The caller owns `*out_json` and must free it with
// `lance_string_free`.
//
// - `criteria_json`: optional JSON object `{"for_column"?: string,
//   "has_name"?: string, "must_support_fts"?: bool,
//   "must_support_exact_equality"?: bool}`, or NULL for all indices.
//
// # Safety
//
// `ds` must be a valid handle, `criteria_json` NULL or a valid C string,
// and `out_json` valid for writes.
int32_t lance_dataset_describe_indices(const struct LanceDataset *ds,
                                       const char *criteria_json,
                                       char **out_json);

// Loads index metadata matching the criteria as a JSON array of
// `lance_dataset_list_indices`-shaped objects (an empty array when nothing
// matches). The caller owns `*out_json` and must free it with
// `lance_string_free`.
//
// - `criteria_json`: optional JSON object `{"uuid"?: string,
//   "name"?: string}`. `uuid` and `name` are mutually exclusive: `uuid`
//   selects the index segment with that build UUID, `name` selects all
//   (delta) segments of the index with that name, and NULL / `{}` selects
//   every index.
//
// # Safety
//
// `ds` must be a valid handle, `criteria_json` NULL or a valid C string,
// and `out_json` valid for writes.
int32_t lance_dataset_load_indices_by_criteria(const struct LanceDataset *ds,
                                               const char *criteria_json,
                                               char **out_json);

// Remaps the index on `columns` to row addresses moved by a compaction
// that ran with `defer_index_remap` (which records the moves in the
// fragment reuse index). Upon success a new dataset version may be
// committed and the handle is updated to it. When there is nothing to
// remap the call is a no-op. Fails if no fragment reuse index exists.
//
// - `columns`: NULL-terminated array of column names (currently exactly
//   one). Must not be NULL.
// - `name`: optional index name, or NULL for the Lance default
//   (`<column>_idx`).
//
// # Safety
//
// `ds` must be a valid handle, `columns` a valid NULL-terminated array of
// C strings, and `name` NULL or a valid C string.
int32_t lance_dataset_remap_column_index(struct LanceDataset *ds,
                                         const char *const *columns,
                                         const char *name);

// Compacts small data files of the dataset into larger ones, committing the
// result as a new version.
//
// - `options_json`: optional JSON object
//   `{"target_rows_per_fragment"?: uint, "max_rows_per_group"?: uint,
//   "max_bytes_per_file"?: uint, "materialize_deletions"?: bool,
//   "materialize_deletions_threshold"?: float, "num_threads"?: uint,
//   "batch_size"?: uint, "io_buffer_size"?: uint,
//   "defer_index_remap"?: bool}`, or NULL for defaults.
// - `out_json`: receives the compaction metrics as JSON
//   `{"fragments_removed": uint, "fragments_added": uint,
//   "files_removed": uint, "files_added": uint}`. Free it with
//   `lance_string_free`.
//
// # Safety
//
// `ds` must be a valid handle, `options_json` NULL or a valid C string, and
// `out_json` valid for writes.
int32_t lance_dataset_compact_files(struct LanceDataset *ds,
                                    const char *options_json,
                                    char **out_json);

// Removes old dataset versions (and files unique to them) from storage.
// Removed versions can no longer be checked out or restored.
//
// - `options_json`: optional JSON object
//   `{"older_than_seconds"?: int (default 1209600, i.e. two weeks),
//   "delete_unverified"?: bool, "error_if_tagged_old_versions"?: bool}`,
//   or NULL for defaults.
// - `out_json`: receives the removal statistics as JSON
//   `{"bytes_removed": uint, "old_versions": uint,
//   "data_files_removed": uint, "transaction_files_removed": uint,
//   "index_files_removed": uint, "deletion_files_removed": uint}`. Free it
//   with `lance_string_free`.
//
// # Safety
//
// `ds` must be a valid handle, `options_json` NULL or a valid C string, and
// `out_json` valid for writes.
int32_t lance_dataset_cleanup_old_versions(const struct LanceDataset *ds,
                                           const char *options_json,
                                           char **out_json);

// Deletes rows matching an SQL predicate and commits a new version.
//
// - `ds`: dataset handle, updated in place to the new version on success.
// - `predicate`: SQL filter selecting the rows to delete. Must not be NULL.
// - `out_json`: if non-NULL, receives `{"num_deleted_rows": uint}` as an
//   owned string (free with `lance_string_free`).
//
// # Safety
//
// `ds` must be a valid handle, `predicate` a valid C string, and `out_json`
// NULL or valid for writes.
int32_t lance_dataset_delete(struct LanceDataset *ds, const char *predicate, char **out_json);

// Updates column values on rows matching an optional SQL predicate and
// commits a new version.
//
// - `ds`: dataset handle, updated in place to the new version on success.
// - `update_json`: required JSON object
//   `{"set": {"col": "sql_expr", ...}, "where"?: string,
//   "conflict_retries"?: uint, "retry_timeout_ms"?: uint}`. `set` must be
//   non-empty. Omitting `where` updates every row.
// - `out_json`: if non-NULL, receives `{"rows_updated": uint}` as an owned
//   string (free with `lance_string_free`).
//
// # Safety
//
// `ds` must be a valid handle, `update_json` a valid C string, and
// `out_json` NULL or valid for writes.
int32_t lance_dataset_update(struct LanceDataset *ds, const char *update_json, char **out_json);

// Merges an Arrow stream of source rows into the dataset (upsert /
// find-or-create / replace-range) and commits a new version.
//
// - `ds`: dataset handle, updated in place to the new version on success.
// - `options_json`: required JSON object
//   `{"on": ["col", ...],
//   "when_matched"?: "update_all"|"do_nothing"|"delete"|"fail"|{"update_if": expr},
//   "when_not_matched"?: "insert_all"|"do_nothing",
//   "when_not_matched_by_source"?: "keep"|"delete"|{"delete_if": expr},
//   "conflict_retries"?: uint, "retry_timeout_ms"?: uint,
//   "source_dedupe_behavior"?: "fail"|"first_seen", "use_index"?: bool,
//   "commit_retries"?: uint, "skip_auto_cleanup"?: bool}`.
//   Defaults mirror Lance's find-or-create semantics: matched rows are kept
//   as-is (`do_nothing`), unmatched source rows are inserted (`insert_all`),
//   target rows missing from the source are kept (`keep`), with 10 conflict
//   retries over at most 30 seconds. `update_if` expressions reference the
//   joined row via `target.` / `source.` qualifiers. `delete_if` expressions
//   reference target columns directly. `source_dedupe_behavior` defaults to
//   `fail` (error when the source has duplicate keys that match the same
//   target row). `use_index` defaults to true (use a scalar index on the
//   join key when one exists). `commit_retries` (default 20) is the inner
//   manifest-conflict retry count, distinct from `conflict_retries`.
//   `skip_auto_cleanup` defaults to false.
// - `stream`: Arrow C stream with the source rows. Ownership is always
//   taken, even on error, so the producer is released exactly once. Must not
//   be NULL.
// - `out_json`: if non-NULL, receives the merge statistics as an owned
//   string (free with `lance_string_free`):
//   `{"num_inserted_rows": uint, "num_updated_rows": uint,
//   "num_deleted_rows": uint, "num_attempts": uint, "bytes_written": uint,
//   "num_files_written": uint, "num_skipped_duplicates": uint}`.
//
// # Safety
//
// All pointer arguments must satisfy the contracts above.
int32_t lance_dataset_merge_insert(struct LanceDataset *ds,
                                   const char *options_json,
                                   struct ArrowArrayStream *stream,
                                   char **out_json);

// Creates a new cancellation token handle. Never fails. Release it with
// [`lance_cancel_token_free`].
struct LanceCancelToken *lance_cancel_token_new(void);

// Cancels the token, waking every FFI call currently racing against it.
// Callable from ANY thread (this is the whole point: the Go side calls it
// from a watcher goroutine while another OS thread is blocked inside an FFI
// call). NULL is a no-op. Cancelling more than once is a no-op.
//
// # Safety
//
// `t` must be NULL or a live handle from [`lance_cancel_token_new`] that has
// not been freed.
void lance_cancel_token_cancel(const struct LanceCancelToken *t);

// Releases a cancellation token handle. NULL is a no-op. Safe to call after
// [`lance_cancel_token_cancel`]; threads that cloned the inner token via
// [`lance_thread_set_cancel_token`] are unaffected (the token is
// reference-counted internally).
//
// # Safety
//
// `t` must be NULL or a handle from [`lance_cancel_token_new`] not already
// freed, and must not be used again afterwards.
void lance_cancel_token_free(struct LanceCancelToken *t);

// Installs (a clone of) the token in the calling thread's cancellation slot,
// making subsequent `block_on_cc!`-based FFI calls on THIS thread
// cancellable. NULL clears the slot. The Go side pairs a set/clear around
// each cancellable FFI call while the goroutine is pinned to its OS thread.
//
// # Safety
//
// `t` must be NULL or a live handle from [`lance_cancel_token_new`] that has
// not been freed.
void lance_thread_set_cancel_token(const struct LanceCancelToken *t);

// Reports whether the calling thread is currently executing inside the shared
// tokio runtime (returns `1` if so, `0` otherwise).
//
// This is `true` exactly on the threads where a nested [`block_on`] would
// panic: the `block_on` driver thread, runtime worker threads, and blocking
// threads. The Go side calls this at the start of every fallible FFI call
// (`ffiCall`) to reject re-entrant calls made from inside a synchronous Go
// callback, converting a would-be Tokio panic into a specific, catchable Go
// error (`ErrReentrantCall`) before the outer FFI guard is needed.
//
// Non-fallible (top-level) Go calls never run on a runtime thread, so this
// returns `0` for them and they proceed normally.
int32_t lance_in_tokio_runtime(void);

// Test-only support for the Go cancellation tests: a fallible export whose
// entire body is a cancellable sleep. Lets the Go side verify the
// set-token / cancel / `ERROR_CODE_CANCELLED` round trip without needing a
// slow real dataset operation.
int32_t lance_test_cancellable_sleep(uint64_t millis);

// Creates a scanner over `ds`.
//
// - `scan_json`: optional JSON object
//   `{"columns"?: [string], "projection_exprs"?: [[name, sql_expr]],
//   "filter"?: string, "filter_substrait"?: base64 string,
//   "prefilter"?: bool, "limit"?: int, "offset"?: int,
//   "with_row_id"?: bool, "with_row_address"?: bool, "batch_size"?: uint,
//   "batch_size_bytes"?: uint, "strict_batch_size"?: bool,
//   "scan_in_order"?: bool,
//   "order_by"?: [{"column": string, "ascending"?: bool,
//   "nulls_first"?: bool}],
//   "aggregate"?: {"group_by"?: [string], "aggregates": [{"func":
//   "count"|"sum"|"avg"|"min"|"max", "column"?: string, "alias"?: string}]},
//   "fragment_ids"?: [uint], "include_deleted_rows"?: bool,
//   "use_stats"?: bool, "use_scalar_index"?: bool,
//   "materialization_style"?: "heuristic"|"all_late"|"all_early",
//   "blob_handling"?: "all_binary"|"blobs_descriptions"|"all_descriptions",
//   "disable_scoring_autoprojection"?: bool, "io_buffer_size"?: uint,
//   "batch_readahead"?: uint, "fragment_readahead"?: uint,
//   "target_parallelism"?: uint,
//   "column"?: string, "k"?: uint, "metric"?: string, "nprobes"?: uint,
//   "minimum_nprobes"?: uint, "maximum_nprobes"?: uint, "refine"?: uint,
//   "ef"?: uint, "use_index"?: bool, "fast_search"?: bool,
//   "distance_lower"?: float, "distance_upper"?: float,
//   "query_parallelism"?: int, "approx_mode"?: "fast"|"normal"|"accurate",
//   "index_segments"?: [uuid string],
//   "fts"?: object, "fts_columns"?: [string], "fts_limit"?: int,
//   "wand_factor"?: float, "scan_stats_plugin"?: uint}`, or NULL for a full
//   scan. Unknown fields are ignored. `distance_lower`/`distance_upper`,
//   `query_parallelism` and `approx_mode` only take effect when a query
//   vector is given. `scan_stats_plugin` is a Go plugin handle invoked once
//   after the scan executes with a JSON summary-statistics payload (see
//   `SCAN_STATS_REPORT`); its registration is released when the scanner
//   drops.
// - `query_vector` / `query_schema`: optional Arrow C Data Interface query
//   vector for nearest-neighbor search (a Float16/32/64 or UInt8 values
//   array, or a (FixedSize)List thereof). Both NULL or both non-NULL.
//   Ownership of both structs is always taken, even on error. When given,
//   `"column"` must be set in `scan_json` (`"k"` defaults to 10).
// - `out`: receives the scanner handle on success. Release it with
//   `lance_scanner_close`.
//
// # Safety
//
// `ds` must be a valid dataset handle, `scan_json` NULL or a valid C
// string, `query_vector`/`query_schema` NULL or valid unmoved Arrow C
// structs, and `out` valid for writes.
int32_t lance_scanner_new(const struct LanceDataset *ds,
                          const char *scan_json,
                          struct ArrowArray *query_vector,
                          struct ArrowSchema *query_schema,
                          struct LanceScanner **out);

// Executes the scan and exports the results into `out` as an Arrow C
// stream. The caller owns the stream and must call its `release` callback.
// The stream is self-contained: the scanner (and dataset) handles may be
// closed while it is still being consumed.
//
// # Safety
//
// `sc` must be a valid scanner handle and `out` valid for writes (any
// previous contents are overwritten without being released).
int32_t lance_scanner_to_stream(const struct LanceScanner *sc, struct ArrowArrayStream *out);

// Executes the scan, collects every result batch and exports the combined
// single batch into `out` as a one-batch Arrow C stream. The caller owns
// the stream and must call its `release` callback. Prefer
// `lance_scanner_to_stream` for large results: this call materializes the
// whole result in memory.
//
// # Safety
//
// `sc` must be a valid scanner handle and `out` valid for writes (any
// previous contents are overwritten without being released).
int32_t lance_scanner_to_batch(const struct LanceScanner *sc, struct ArrowArrayStream *out);

// Counts the rows the scan would produce (respecting the scanner's filter).
//
// # Safety
//
// `sc` must be a valid scanner handle and `out` valid for writes.
int32_t lance_scanner_count_rows(const struct LanceScanner *sc, uint64_t *out);

// Returns a human-readable description of the scan's execution plan. The
// caller owns `*out_plan` and must free it with `lance_string_free`.
//
// # Safety
//
// `sc` must be a valid scanner handle and `out_plan` valid for writes.
int32_t lance_scanner_explain(const struct LanceScanner *sc, bool verbose, char **out_plan);

// EXPLAIN ANALYZE: executes the scan and returns the execution plan
// annotated with runtime metrics. `mode` 0 analyzes the scan's own plan.
// `mode` 1 analyzes the equivalent COUNT(*) plan (the plan `count_rows`
// would execute). Note this call runs the full scan. The caller owns
// `*out_text` and must free it with `lance_string_free`.
//
// # Safety
//
// `sc` must be a valid scanner handle and `out_text` valid for writes.
int32_t lance_scanner_analyze(const struct LanceScanner *sc, int32_t mode, char **out_text);

// Releases a scanner handle. NULL is a no-op. The handle must not be used
// again afterwards. Streams previously exported from this scanner remain
// valid.
//
// # Safety
//
// `sc` must be NULL or a handle obtained from `lance_scanner_new` that has
// not already been closed.
void lance_scanner_close(struct LanceScanner *sc);

// Creates a session with in-memory index and metadata caches of the given
// byte budgets. `out` receives the handle. Release it with
// `lance_session_close`.
//
// # Safety
//
// `out` must be valid for writes.
int32_t lance_session_new(uint64_t index_cache_bytes,
                          uint64_t metadata_cache_bytes,
                          struct LanceSession **out);

// Creates a session whose index cache is backed by the Go plugin registered
// under `plugin_handle` (a `CacheBackend`). Only serializable, codec-bearing
// index entries reach the Go backend, and live (non-serializable) objects stay
// in an embedded in-process cache. The metadata cache stays in-memory
// (Lance 8.0 exposes no metadata-cache backend hook).
//
// # Safety
//
// `plugin_handle` must be a live Go plugin handle, and `out` must be valid for
// writes.
int32_t lance_session_new_with_cache_backend(size_t plugin_handle,
                                             uint64_t metadata_cache_bytes,
                                             struct LanceSession **out);

// Writes session cache statistics into `*out_json` as a JSON object
// `{"index_cache": CacheStats, "metadata_cache": CacheStats,
// "size_bytes": uint, "approx_num_items": uint}` where each `CacheStats` is
// `{"hits","misses","num_entries","size_bytes"}`. The caller owns the string
// and must free it with `lance_string_free`.
//
// # Safety
//
// `sess` must be a valid session handle and `out_json` valid for writes.
int32_t lance_session_stats(const struct LanceSession *sess, char **out_json);

// Releases a session handle. NULL is a no-op.
//
// # Safety
//
// `sess` must be NULL or a handle from `lance_session_new` /
// `lance_session_new_with_cache_backend` not already closed.
void lance_session_close(struct LanceSession *sess);

// Opens a dataset sharing `sess`'s caches. Same `uri`/`storage_kv`/
// `options_json` contract as `lance_dataset_open` (minus the cache-size
// options, which the session owns). `out` receives the dataset handle.
//
// # Safety
//
// All pointer arguments must satisfy the usual FFI contracts. `sess` must be
// a valid session handle and `out` valid for writes.
int32_t lance_dataset_open_with_session(const char *uri,
                                        const char *const *storage_kv,
                                        const char *options_json,
                                        const struct LanceSession *sess,
                                        struct LanceDataset **out);

// Writes an Arrow stream to a dataset, optionally sharing a session's caches
// and/or reporting progress to a Go callback.
//
// - `stream`: Arrow C stream of record batches, ownership always taken.
// - `options_json`: same complete write-options object accepted by
//   `lance_dataset_write`, or NULL.
// - `sess`: session handle to attach (NULL for none).
// - `progress_handle`: Go write-progress plugin handle (0 for none). The
//   plugin's method `WRITE_PROGRESS_REPORT` is invoked after each batch with
//   a 20-byte little-endian `WriteStats` payload.
// - `out`: receives the resulting dataset handle (NULL to discard).
//
// # Safety
//
// All pointer arguments must satisfy the usual FFI contracts.
int32_t lance_dataset_write_with_session(struct ArrowArrayStream *stream,
                                         const char *uri,
                                         const char *options_json,
                                         const char *const *storage_kv,
                                         const struct LanceSession *sess,
                                         size_t progress_handle,
                                         struct LanceDataset **out);

// Runs a SQL query against the dataset and exports the results into `out`
// as an Arrow C stream. The underlying engine is DataFusion, and the dataset is
// registered as a table named by `"table_name"` (default `"dataset"`).
//
// - `sql`: the SQL query text. Must not be NULL.
// - `options_json`: optional JSON object `{"table_name"?: string,
//   "with_row_id"?: bool, "with_row_addr"?: bool}`, or NULL for defaults.
// - `out`: receives a self-contained Arrow C stream. The caller owns it and
//   must call its `release` callback. It stays valid after the dataset
//   handle is closed.
//
// # Safety
//
// `ds` must be a valid handle, `sql` a valid C string, `options_json` NULL
// or a valid C string, and `out` valid for writes (previous contents are
// overwritten without release).
int32_t lance_dataset_sql(const struct LanceDataset *ds,
                          const char *sql,
                          const char *options_json,
                          struct ArrowArrayStream *out);

// Takes specific rows from the dataset and returns them as a one-batch
// Arrow C stream.
//
// - `spec_json`: JSON object with exactly one of `"indices"` (row offsets),
//   `"row_ids"` (stable row ids) or `"addresses"` (row addresses), plus
//   optionally `"columns"`: [string] or `"sql_projection"`:
//   `[{"name": string, "expr": string}]` (mutually exclusive) and
//   `"with_row_address"`: bool. Must not be NULL.
// - `out`: receives a self-contained Arrow C stream producing exactly one
//   batch with the requested rows in request order. The caller owns it and
//   must call its `release` callback.
//
// # Safety
//
// `ds` must be a valid handle, `spec_json` a valid C string, and `out`
// valid for writes (previous contents are overwritten without release).
int32_t lance_dataset_take(const struct LanceDataset *ds,
                           const char *spec_json,
                           struct ArrowArrayStream *out);

// Streams batches for a list of `[start, end)` row-offset ranges.
//
// - `spec_json`: JSON object `{"ranges": [[uint, uint], ...],
//   "columns"?: [string], "batch_readahead"?: uint}`. Must not be NULL.
// - `out`: receives a self-contained Arrow C stream. The caller owns it and
//   must call its `release` callback. It stays valid after the dataset
//   handle is closed.
//
// # Safety
//
// `ds` must be a valid handle, `spec_json` a valid C string, and `out`
// valid for writes (previous contents are overwritten without release).
int32_t lance_dataset_take_scan(const struct LanceDataset *ds,
                                const char *spec_json,
                                struct ArrowArrayStream *out);

// Randomly samples `n` rows from the dataset and returns them (in row-id
// order, not random order) as a one-batch Arrow C stream.
//
// - `spec_json`: JSON object `{"n": uint, "columns"?: [string],
//   "fragment_ids"?: [uint]}`. Must not be NULL.
// - `out`: receives a self-contained one-batch Arrow C stream. The caller
//   owns it and must call its `release` callback.
//
// # Safety
//
// `ds` must be a valid handle, `spec_json` a valid C string, and `out`
// valid for writes (previous contents are overwritten without release).
int32_t lance_dataset_sample(const struct LanceDataset *ds,
                             const char *spec_json,
                             struct ArrowArrayStream *out);

// Frees a `(ptr, len)` byte buffer previously handed out by this crate (e.g.
// `lance_write_fragments` or the blob-read functions). NULL is a no-op. `len`
// must be the exact length that was returned alongside `ptr`.
//
// # Safety
//
// `ptr` must be NULL or a pointer previously returned by this crate with the
// matching `len`, not already freed.
void lance_bytes_free(uint8_t *ptr, size_t len);

// Writes `stream`'s batches as new, uncommitted fragments at `uri` and
// returns the resulting [`Transaction`] both as lossless protobuf bytes
// (`out_txn_pb` / `out_txn_pb_len`, freed with [`lance_bytes_free`]) and as
// a JSON summary (`out_txn_json`, freed with `lance_string_free`).
//
// This is the distributed-write primitive: run it on N workers over disjoint
// data, ship the N transactions to a driver, and commit them with
// `lance_commit` / `lance_commit_batch`.
//
// - `stream`: caller-produced Arrow C stream, ownership is always taken.
// - `uri`: destination dataset URI. Must not be NULL.
// - `options_json`: optional `{"max_rows_per_file"?, "max_rows_per_group"?,
//   "max_bytes_per_file"?, "data_storage_version"?, "enable_stable_row_ids"?,
//   "enable_v2_manifest_paths"?, "transaction_properties"?}`.
// - `storage_kv`: storage options, same format as `lance_dataset_open`.
//
// # Safety
//
// All pointer arguments must satisfy the contracts above, and the `out_*`
// pointers must be non-NULL and valid for writes.
int32_t lance_write_fragments(struct ArrowArrayStream *stream,
                              const char *uri,
                              const char *options_json,
                              const char *const *storage_kv,
                              uint8_t **out_txn_pb,
                              size_t *out_txn_pb_len,
                              char **out_txn_json);

// Commits a single [`Transaction`] (as `pb::Transaction` bytes produced by
// `lance_write_fragments`) against the dataset at `uri`, returning a handle
// to the resulting dataset version in `out`.
//
// With `"detached": true` in `options_json` the version is committed
// OUTSIDE the dataset's lineage (it never appears in the history and can
// never become latest; requires V2 manifest paths and an existing dataset).
// The full transaction — uuid, tag, transaction properties — is preserved,
// and the returned handle is checked out at the detached version (its
// version number carries the detached high bit).
//
// # Safety
//
// `txn_pb` must point to `txn_pb_len` valid bytes. All other pointer
// contracts as documented on the sibling functions.
int32_t lance_commit(const char *uri,
                     const uint8_t *txn_pb,
                     size_t txn_pb_len,
                     const char *options_json,
                     const char *const *storage_kv,
                     struct LanceDataset **out);

// Commits a batch of append [`Transaction`]s (each as `pb::Transaction`
// bytes) in a single commit against `uri`. Lance merges compatible appends
// into one manifest, so the result is a single new version, returned as JSON
// `{"version": uint}` in `out_json`.
//
// - `txns_pb`: array of `num_txns` pointers to protobuf buffers.
// - `txns_pb_lens`: array of `num_txns` matching lengths.
//
// # Safety
//
// The two arrays must each hold `num_txns` valid entries, and `txns_pb[i]` must
// point to `txns_pb_lens[i]` valid bytes.
int32_t lance_commit_batch(const char *uri,
                           const uint8_t *const *txns_pb,
                           const size_t *txns_pb_lens,
                           size_t num_txns,
                           const char *options_json,
                           const char *const *storage_kv,
                           char **out_json);

// Returns the location of the manifest backing the currently checked-out
// version as JSON `{"version": uint, "path": string, "size": uint|null,
// "naming_scheme": "V1"|"V2", "e_tag": string|null}`. The caller owns
// `*out_json` and must free it with `lance_string_free`.
//
// # Safety
//
// `ds` must be a valid handle and `out_json` valid for writes.
int32_t lance_dataset_manifest_location(const struct LanceDataset *ds, char **out_json);

// Reads the transaction that produced the currently checked-out version.
// See [`emit_optional_transaction`] for the `None` encoding.
//
// # Safety
//
// `ds` must be a valid handle, and the `out_*` pointers valid for writes.
int32_t lance_dataset_read_transaction(const struct LanceDataset *ds,
                                       uint8_t **out_pb,
                                       size_t *out_pb_len,
                                       char **out_json);

// Reads the transaction that produced `version`.
//
// # Safety
//
// As [`lance_dataset_read_transaction`].
int32_t lance_dataset_read_transaction_by_version(const struct LanceDataset *ds,
                                                  uint64_t version,
                                                  uint8_t **out_pb,
                                                  size_t *out_pb_len,
                                                  char **out_json);

// Returns up to `n` most recent transactions as a JSON array of transaction
// views (missing/unreadable entries appear as `null`).
//
// # Safety
//
// `ds` must be a valid handle and `out_json` valid for writes.
int32_t lance_dataset_get_transactions(const struct LanceDataset *ds, size_t n, char **out_json);

// Returns a JSON summary of the current manifest:
// `{"version", "fields": [{"id", "name"}], "num_fragments", "config",
// "table_metadata", "tag", "branch"}`.
//
// # Safety
//
// `ds` must be a valid handle and `out_json` valid for writes.
int32_t lance_dataset_manifest(const struct LanceDataset *ds, char **out_json);

// Returns detached manifests as a JSON array of
// `{"version", "path", "size"?}` objects.
//
// # Safety
//
// `ds` must be a valid handle and `out_json` valid for writes.
int32_t lance_dataset_list_detached_manifests(const struct LanceDataset *ds, char **out_json);

// Builds an [`Operation`] from JSON, wraps it in a fresh [`Transaction`] at
// `read_version`, and commits it against `uri`.
//
// - `operation_json`: a tagged object, e.g.
//   `{"type": "UpdateConfig", "config_updates": {"entries": {"k": "v"}}}`
//   or `{"type": "Restore", "version": 1}`.
// - `read_version`: the dataset version the operation is based on.
//
// # Safety
//
// Pointer contracts as documented. `out` must be valid for writes.
int32_t lance_dataset_commit_operation(const char *uri,
                                       const char *operation_json,
                                       uint64_t read_version,
                                       const char *options_json,
                                       const char *const *storage_kv,
                                       struct LanceDataset **out);

// Checks out a historical version of the dataset as a NEW handle.
//
// - `ref_json`: `{"version": uint}` or `{"tag": string}`. Must not be NULL.
// - `out`: receives a new dataset handle fixed at the requested version.
//   Release it with `lance_dataset_close`. The original handle `ds` remains
//   valid and unchanged.
//
// # Safety
//
// `ds` must be a valid handle, `ref_json` a valid C string, and `out` valid
// for writes.
int32_t lance_dataset_checkout(const struct LanceDataset *ds,
                               const char *ref_json,
                               struct LanceDataset **out);

// Checks out the latest committed version on this handle (useful after
// another writer committed, or after `lance_dataset_restore` on a different
// handle).
//
// # Safety
//
// `ds` must be a valid handle.
int32_t lance_dataset_checkout_latest(struct LanceDataset *ds);

// Commits the currently checked-out version of this handle as the new
// latest version of the dataset. Typically used on a handle produced by
// `lance_dataset_checkout` to roll the dataset back.
//
// # Safety
//
// `ds` must be a valid handle.
int32_t lance_dataset_restore(struct LanceDataset *ds);

// Lists all committed versions of the dataset, oldest first, as JSON
// `[{"version": uint, "timestamp": string, "metadata": {..}}, ...]`. The
// caller owns `*out_json` and must free it with `lance_string_free`.
//
// # Safety
//
// `ds` must be a valid handle and `out_json` valid for writes.
int32_t lance_dataset_list_versions(const struct LanceDataset *ds, char **out_json);

// Creates a tag pointing at the referenced version. Fails if the tag
// already exists.
//
// - `tag`: tag name. Must not be NULL.
// - `ref_json`: `{"version": uint}` or `{"tag": string}`. Must not be NULL.
//
// # Safety
//
// `ds` must be a valid handle and the strings valid C strings.
int32_t lance_dataset_tag_create(const struct LanceDataset *ds,
                                 const char *tag,
                                 const char *ref_json);

// Moves an existing tag to the referenced version.
//
// # Safety
//
// Same contracts as `lance_dataset_tag_create`.
int32_t lance_dataset_tag_update(const struct LanceDataset *ds,
                                 const char *tag,
                                 const char *ref_json);

// Deletes a tag.
//
// # Safety
//
// `ds` must be a valid handle and `tag` a valid C string.
int32_t lance_dataset_tag_delete(const struct LanceDataset *ds, const char *tag);

// Lists all tags of the dataset as a JSON object
// `{"<tag>": {"branch": string|null, "version": uint,
// "manifestSize": uint, "metadata": {..}, ...}, ...}`. The caller owns
// `*out_json` and must free it with `lance_string_free`.
//
// # Safety
//
// `ds` must be a valid handle and `out_json` valid for writes.
int32_t lance_dataset_tag_list(const struct LanceDataset *ds, char **out_json);

// Returns the full contents of a single tag as JSON
// `{"branch": string|null, "version": uint, "createdAt"?: string,
// "updatedAt"?: string, "manifestSize": uint, "metadata": {..}}` (the same
// per-tag shape as `lance_dataset_tag_list`). The caller owns `*out_json`
// and must free it with `lance_string_free`.
//
// # Safety
//
// `ds` must be a valid handle, `tag` a valid C string, and `out_json` valid
// for writes.
int32_t lance_dataset_tag_contents(const struct LanceDataset *ds, const char *tag, char **out_json);

// Resolves a tag to its version number.
//
// # Safety
//
// `ds` must be a valid handle, `tag` a valid C string, and `out` valid for
// writes.
int32_t lance_dataset_tag_get_version(const struct LanceDataset *ds,
                                      const char *tag,
                                      uint64_t *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* LANCE_GO_H */
